# Generated by Django 6.0.3 on 2026-08-26 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(default='Everyone', max_length=20)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('posted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Wisbees', max_length=200)),
                ('company_address', models.TextField(default=' Mumbai, Maharashtra 400001')),
                ('company_email', models.CharField(default='info@wisbees.com', max_length=120)),
                ('company_phone', models.CharField(default='+91 0000000000', max_length=20)),
                ('offer_letter_template', models.TextField(blank=True, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('nda_path', models.CharField(blank=True, max_length=200, null=True)),
                ('letterhead_path', models.CharField(blank=True, max_length=200, null=True)),
                ('nda_data', models.BinaryField(blank=True, null=True)),
                ('nda_filename', models.CharField(blank=True, max_length=200, null=True)),
                ('letterhead_data', models.BinaryField(blank=True, null=True)),
                ('letterhead_mime', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.FloatField(default=0)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('offer_sent', models.BooleanField(default=False)),
                ('nda_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emp_type', models.CharField(default='Normal', max_length=20)),
                ('gender', models.CharField(default='female', max_length=10)),
                ('profile_pic_data', models.BinaryField(blank=True, null=True)),
                ('profile_pic_mime', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('designation', models.CharField(default='HR Manager', max_length=100)),
                ('department', models.CharField(default='Human Resources', max_length=100)),
                ('signature_path', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_data', models.BinaryField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hr',
            },
        ),
        migrations.CreateModel(
            name='NewsletterJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('post_slug', models.CharField(db_index=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'newsletter_job',
            },
        ),
        migrations.CreateModel(
            name='NewsletterUnsubscribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'newsletter_unsubscribe',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrms.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='hrms.employee')),
            ],
            options={
                'db_table': 'employee_accounts',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.hr'),
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_email', models.CharField(blank=True, max_length=120, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('hr', models.ForeignKey(blank=True, db_column='hr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.hr')),
            ],
            options={
                'db_table': 'email_config',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hrms.employee')),
            ],
            options={
                'db_table': 'leave_request',
            },
        ),
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='hrms.newsletterjob')),
            ],
            options={
                'db_table': 'newsletter_delivery',
            },
        ),
        migrations.CreateModel(
            name='OfferLetterDraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_key', models.CharField(blank=True, max_length=120, null=True)),
                ('role_title', models.CharField(blank=True, max_length=200, null=True)),
                ('full_letter_text', models.TextField(blank=True, null=True)),
                ('email_body_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='offer_draft', to='hrms.employee')),
            ],
            options={
                'db_table': 'offer_letter_draft',
            },
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('form_data', models.TextField()),
                ('chart_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.employeeaccount')),
            ],
            options={
                'db_table': 'research_reports',
            },
        ),
    ]
