# Generated by Django 6.0.3 on 2026-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
