# Generated by Django 6.0.3 on 2026-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_employee_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='departments_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='durations_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='roles_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
