# Generated by Django 6.0.3 on 2026-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_companysettings_departments_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
