# Generated by Django 6.0.3 on 2026-09-29 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_employee_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrackerConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cutoff_hours', models.IntegerField(default=24)),
                ('task_types_json', models.TextField(default='["Major", "Minor"]')),
                ('custom_fields_json', models.TextField(default='[]')),
                ('auto_lock_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_tracker_config',
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('day_number', models.IntegerField(default=1)),
                ('day_status', models.CharField(default='Working Day', max_length=30)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('manager_rating', models.IntegerField(default=0)),
                ('manager_remarks', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_trackers', to='hrms.employee')),
            ],
            options={
                'db_table': 'daily_tracker_day',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('performed_by_name', models.CharField(max_length=100)),
                ('performed_by_role', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.employee')),
                ('tracker_day', models.ForeignKey(blank=True, db_column='tracker_day_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='hrms.dailytrackerday')),
            ],
            options={
                'db_table': 'daily_tracker_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskRow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField()),
                ('task_type', models.CharField(default='Major', max_length=50)),
                ('hours_worked', models.FloatField(default=0.0)),
                ('is_achievement', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('custom_data', models.TextField(blank=True, null=True)),
                ('tracker_day', models.ForeignKey(db_column='tracker_day_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hrms.dailytrackerday')),
            ],
            options={
                'db_table': 'daily_task_row',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrackerUnlockRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='tracker_unlock_requests', to='hrms.employee')),
                ('tracker_day', models.ForeignKey(db_column='tracker_day_id', on_delete=django.db.models.deletion.CASCADE, related_name='unlock_requests', to='hrms.dailytrackerday')),
            ],
            options={
                'db_table': 'daily_tracker_unlock_request',
                'ordering': ['-requested_at'],
            },
        ),
    ]
