# Generated by Django 6.0.3 on 2026-09-30 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_dailytrackerconfig_dailytrackerday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskrow',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailytaskrow',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='managed_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hrms.employee'),
        ),
        migrations.CreateModel(
            name='DailyAssignedTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('task_type', models.CharField(default='Major', max_length=50)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_created', to='hrms.employee')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_received', to='hrms.employee')),
            ],
            options={
                'db_table': 'daily_assigned_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailytaskrow',
            name='assigned_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_log_rows', to='hrms.dailyassignedtask'),
        ),
    ]
